services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"

  backend:
    build:
      context: ../src/backend # Django プロジェクトがある場所
      dockerfile: ../../environment/backend/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: backend
    volumes:
      - ../src/backend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
    depends_on:
      - db
      - mailhog
    user: "${UID}:${GID}"

  frontend:
    build:
      context: ../src/frontend
      dockerfile: ../../environment/frontend/Dockerfile
    container_name: frontend
    volumes:
      - ../src/frontend:/app
      - /app/node_modules
    working_dir: /app
    command: yarn dev
    ports:
      - "3000:3000"
    user: "${UID}:${GID}"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  db-data:
